SET IDENTITY_INSERT [dbo].[ServiceUsers] ON
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (1, N'Aaron Copland', N'acopland@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (2, N'Aaron Goldberg', N'agoldberg@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (3, N'Ryan Corbin', N'rcorbin@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (4, N'Aidan Mayes', N'amayes@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (5, N'Adrian Smith', N'asmith@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (6, N'Aisha Tyler', N'atyler@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (7, N'Aaron Copland', N'acopland@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (8, N'Aaron Goldberg', N'agoldberg@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (9, N'Ryan Corbin', N'rcorbin@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (10, N'Aidan Mayes', N'amayes@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (11, N'Adrian Smith', N'asmith@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (12, N'Aisha Tyler', N'atyler@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (13, N'Aaron Copland', N'acopland@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (14, N'Aaron Goldberg', N'agoldberg@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (15, N'Ryan Corbin', N'rcorbin@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (16, N'Aidan Mayes', N'amayes@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (17, N'Adrian Smith', N'asmith@gmail.com', N'adsd', 0)
INSERT INTO [dbo].[ServiceUsers] ([ServiceUserId], [Name], [Email], [Location], [IsShelter]) VALUES (18, N'Aisha Tyler', N'atyler@gmail.com', N'adsd', 0)
SET IDENTITY_INSERT [dbo].[ServiceUsers] OFF
