SET IDENTITY_INSERT [dbo].[Pets] ON
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (1, 1, N'Suzzie', N'Chihuahua', 2, N'Very playful and lovable, loves to cuddle. Has all vaccinations.', N'2 Cups dry dog food throughout the day', N'/Content/ImageResources/placeholder.gif', 1, NULL)
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (2, 2, N'Jamie', N'Maine Coon', 1, N'Still has much of her kitten playfulness, but also makes a great lap cat.', N'3 small tins of wet cat food throughout the day', N'/Content/ImageResources/placeholder.gif', 2, NULL)
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (3, 3, N'Jose', N'Box Turtle', 56, N'Very aggressive, will protect your home from intruders and friends.  No one gets by this Turtle.', N'Freshly chopped vegetable and raw beef', N'/Content/ImageResources/placeholder.gif', 3, NULL)
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (4, 4, N'Whitey', N'Chameleon', 5, N'Blends into society.', N'A spoonful of flies twice a day', N'/Content/ImageResources/placeholder.gif', 4, NULL)
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (5, 5, N'Tom', N'White', 6, N'Hops more than any rabbit.', N'2 Cups dry rabbit food throughout the day', N'/Content/ImageResources/placeholder.gif', 5, NULL)
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (6, 4, N'Jerry', N'Gila Monster', 4, N'He''s a monster.', N'Small birds, mammals, frogs, reptile eggs, etc.', N'/Content/ImageResources/placeholder.gif', 5, NULL)
INSERT INTO [dbo].[Pets] ([PetId], [SpeciesId], [Name], [Breed], [Age], [Description], [Diet], [PetPictureUrl], [UserId], [User_ServiceUserId]) VALUES (7, 6, N'Sam', N'Puffer', 3, N'Follows you through his tank.', N'Fish food 3 times a day', N'/Content/ImageResources/puffer_fish_3084634b.jpg', 6, NULL)
SET IDENTITY_INSERT [dbo].[Pets] OFF
