// <auto-generated />
namespace MVCPetAdoption.DataContexts.PetMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ServiceUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServiceUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201505060012567_ServiceUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
